version: '3.8'

services:
  web_frontend:
    image: nginx:alpine
    container_name: web_frontend
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ./web:/usr/share/nginx/html

  faas_python:
    build: ./faas
    container_name: faas_python
    restart: always
    ports:
      - "5001:5001"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: cadvisor_nicho
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    privileged: true
    devices:
      - /dev/kmsg
