name: Automated Deployment CI/CD
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Deploy Apps via Docker Compose
        run: |
          cd ~/cc_uas/app-layer
          docker-compose pull
          docker-compose up -d --build
